<?php
/**
 * This Software is the property of OXID eSales and is protected
 * by copyright law.
 *
 * Any unauthorized use of this software will be prosecuted by
 * civil and criminal law.
 *
 * @link      http://www.oxid-esales.com
 * @copyright (C) OXID eSales AG 2003-2017
 * @version   OXID eSales Visual CMS
 */

$sLangName = 'Deutsch';

$aLang = array(
    // Charsets
    'charset'                                              => 'UTF-8',
    // 'charset' => 'ISO-8859-15',

    // Lang-Strings
    'DD_VISUAL_EDITOR'                                     => 'Visual CMS',
    'ddoevisualcms'                                        => 'Visual CMS',
    'DD_VISUAL_EDITOR_MAIN'                                => 'Editor',

    'SHOP_MODULE_GROUP_frontend'                           => 'Frontend',
    'SHOP_MODULE_GROUP_backend'                            => 'Backend',
    'SHOP_MODULE_GROUP_other'                              => 'Sonstiges',
    'SHOP_MODULE_blCustomGridFramework'                    => 'Eigenes Gridsystem verwenden (deaktiviert Bootstrap)',
    'SHOP_MODULE_sGridColPrefix'                           => 'Spalten Prefix f&uuml;r CSS-Klasse (Nur bei eigenem Gridsystem)',
    'SHOP_MODULE_sGridOffsetPrefix'                        => 'Spalten Offset Prefix f&uuml;r CSS-Klasse (Nur bei eigenem Gridsystem)',
    'SHOP_MODULE_sGridRow'                                 => 'Zeilen CSS-Klasse (Nur bei eigenem Gridsystem)',
    'SHOP_MODULE_blGridWordNumbers'                        => 'Spaltenzahlen in W&ouml;rter umwandeln [1 = one] (Nur bei eigenem Gridsystem)',
    'SHOP_MODULE_iGridSize'                                => 'Gridgr&ouml;&szlig;e / Spalten pro Zeile (Empfohlen: 12)',
    'SHOP_MODULE_iGridsterSize'                            => 'Gridgr&ouml;&szlig;e im Visual CMS (Empfohlen: 6)',
    'SHOP_MODULE_blDisableJQuery'                          => 'Einbindung von jQuery &uuml;ber das Modul deaktivieren',
    'SHOP_MODULE_blDisableBootstrap'                       => 'Einbindung von Bootstrap &uuml;ber das Modul deaktivieren',
    'SHOP_MODULE_blEnableJQueryMigrate'                    => 'Migrations Script f&uuml;r jQuery 1.9+ laden (Empfohlen bei Verwendung des Azure Themes)',
    'SHOP_MODULE_blVisualEditorDebug'                      => 'Debug-Modus',
    'SHOP_MODULE_blEnableLazyLoading'                      => 'Lazy-Loading für Bilder aktivieren (erfordert jQuery Unveil)',
    'SHOP_MODULE_blEnableFontAwesome'                      => 'Font-Awesome einbinden',

    'DD_VISUAL_EDITOR_NO_ID_GIVEN'                         => 'Bitte w&auml;hlen Sie zun&auml;chst einen CMS-Inhalt aus oder aktivieren Sie die Option &quot;Neue Seite anlegen&quot;.',
    'DD_VISUAL_EDITOR_IDENT_ALREADY_IN_USE'                => 'Ident. wird bereits verwendet, bitte geben Sie einen anderen Ident. an.',

    'DD_VISUAL_EDITOR_SETTINGS_MAIN'                       => 'Einstell.',
    'DD_VISUAL_EDITOR_SETTINGS_ADVANCED'                   => 'Erweitert',
    'DD_VISUAL_EDITOR_SETTINGS_SEO'                        => 'SEO',
    'DD_VISUAL_EDITOR_HELP'                                => 'Hilfe',
    'DD_VISUAL_EDITOR_CONTENT'                             => 'Inhalt',
    'DD_VISUAL_EDITOR_WIDGETS'                             => 'Widgets',
    'DD_VISUAL_EDITOR_WIDGET'                              => 'Widget',
    'DD_VISUAL_EDITOR_ADD_WIDGET'                          => 'Widget hinzuf&uuml;gen',
    'DD_VISUAL_EDITOR_ADD_IMAGE'                           => 'Bild hinzuf&uuml;gen',
    'DD_VISUAL_EDITOR_DELETE_ALL_WIDGETS'                  => 'Alle Widgets l&ouml;schen',
    'DD_VISUAL_EDITOR_SHOW_SOURCE'                         => 'Quelltext anzeigen',
    'DD_VISUAL_EDITOR_SHOW_WIDGETS'                        => 'Widgets anzeigen',
    'DD_VISUAL_EDITOR_ADD_WIDGET_SAVE'                     => 'Speichern',
    'DD_VISUAL_EDITOR_ADD_WIDGET_CANCEL'                   => 'Abbrechen',

    'DD_VISUAL_EDITOR_TYPE'                                => 'Typ',
    'DD_VISUAL_EDITOR_TYPE_BLOCK'                          => 'Block',
    'DD_VISUAL_EDITOR_TYPE_STANDARD'                       => 'Standard',

    'DD_VISUAL_EDITOR_NEW_BLOCK'                           => 'Neuen Block anlegen',
    'DD_VISUAL_EDITOR_BLOCK'                               => 'Block',
    'DD_VISUAL_EDITOR_CHOOSE_BLOCK'                        => 'Block ausw&auml;hlen',
    'DD_VISUAL_EDITOR_BLOCK_OBJECT_TYPE'                   => 'Zuordnung',
    'DD_VISUAL_EDITOR_CHOOSE_BLOCK_OBJECT'                 => 'Zuordnung ausw&auml;hlen',
    'DD_VISUAL_EDITOR_BLOCK_OBJECT_ARTICLE'                => 'Artikel',
    'DD_VISUAL_EDITOR_BLOCK_OBJECT_CATEGORY'               => 'Kategorie',
    'DD_VISUAL_EDITOR_BLOCK_OBJECT_MANUFACTURER'           => 'Hersteller',
    'DD_VISUAL_EDITOR_BLOCK_OBJECT_EMPTY'                  => 'Keine Zuordnung',
    'DD_VISUAL_EDITOR_BLOCK_DELETE'                        => 'L&ouml;schen',
    'DD_VISUAL_EDITOR_BLOCK_DELETE_CONFIRM'                => 'Wollen Sie den Block wirklich L&ouml;schen?',
    'DD_VISUAL_EDITOR_CLEAR_TMP_INFO'                      => 'Das Temp-Verzeichnis muss nach jeder &Auml;nderung geleert werden, damit die Template Dateien neu kompiliert werden k&ouml;nnen.',
    'DD_VISUAL_EDITOR_CLEAR_TMP'                           => 'Temp-Verzeichnis nach dem Speichern leeren',

    'DD_VISUAL_EDITOR_NEW'                                 => 'Neuen Inhalt anlegen',
    'DD_VISUAL_EDITOR_TITLE'                               => 'Titel',
    'DD_VISUAL_EDITOR_IDENT'                               => 'Ident.',
    'DD_VISUAL_EDITOR_IDENT_INFO'                          => 'Leer lassen, um Ident. automatisch generieren zu lassen',
    'DD_VISUAL_EDITOR_FOLDER'                              => 'Ordner',
    'DD_VISUAL_EDITOR_CATEGORY'                            => 'Eingefügt vor',
    'DD_VISUAL_EDITOR_URL'                                 => 'SEO-URL',
    'DD_VISUAL_EDITOR_SNIPPET'                             => 'Snippet',
    'DD_VISUAL_EDITOR_SNIPPET_COPIED'                      => 'Snippet kopiert!',
    'DD_VISUAL_EDITOR_CMS'                                 => 'CMS-Inhalt',
    'DD_VISUAL_EDITOR_CHOOSE_CMS'                          => 'CMS-Inhalt suchen',
    'DD_VISUAL_EDITOR_SAVE'                                => 'Speichern',
    'DD_VISUAL_EDITOR_APPLY'                               => '&Uuml;bernehmen',
    'DD_VISUAL_EDITOR_CANCEL'                              => 'Abbrechen',
    'DD_VISUAL_EDITOR_PREVIEW'                             => 'Vorschau',
    'DD_VISUAL_EDITOR_PREVIEW_POPUP_INFO'                  => 'Info: F&uuml;r die Vorschau m&uuml;ssen Popups zugelassen werden',
    'DD_VISUAL_EDITOR_ACTIVE'                              => 'Aktiv',
    'DD_VISUAL_EDITOR_HIDE_TITLE'                          => '&Uuml;berschrift verbergen',
    'DD_VISUAL_EDITOR_HIDE_TITLE_INFO'                     => 'Nur f&uuml;r statische CMS-Seiten',
    'DD_VISUAL_EDITOR_HIDE_SIDEBAR'                        => 'Sidebar deaktivieren',
    'DD_VISUAL_EDITOR_HIDE_SIDEBAR_INFO'                   => 'Nur f&uuml;r statische CMS-Seiten',
    'DD_VISUAL_EDITOR_FULLWIDTH'                           => 'Fullwidth Layout',
    'DD_VISUAL_EDITOR_IS_LANDING'                          => 'Landing Page',
    'DD_VISUAL_EDITOR_IS_LANDING_INFO'                     => 'Inhalt wird ohne Header, Footer und Sidebar ausgegeben. Gilt nur f&uuml;r statische CMS-Seiten.',
    'DD_VISUAL_EDITOR_ADVANCED_TYPE'                       => 'CMS-Typ',
    'DD_VISUAL_EDITOR_ADVANCED_LAYOUT'                     => 'Layout',
    'DD_VISUAL_EDITOR_ADVANCED_BEHAVIOR'                   => 'Verhalten',
    'DD_VISUAL_EDITOR_USE_PLAIN_CONTENT'                   => 'Widgets deaktivieren und ausschließlich Text verwenden',
    'DD_VISUAL_EDITOR_USE_PLAIN_CONTENT_INFO'              => 'Es wird nur ein Textfeld zur Bearbeitung des Inhaltes angezeigt. Sämtliche Widget- und Layout-Funktionen sind deaktiviert. Diese Option ist n&uuml;tzlich, um Inhalts-Bereiche festzulegen, die kein HTML erlauben.',

    'DD_VISUAL_EDITOR_WIDGET_TYPE'                         => 'Typ',
    'DD_VISUAL_EDITOR_WIDGET_TYPE_TEXT'                    => 'Text',
    'DD_VISUAL_EDITOR_WIDGET_TYPE_ARTICLE'                 => 'Artikel',
    'DD_VISUAL_EDITOR_WIDGET_CONTENT'                      => 'Inhalt',
    'DD_VISUAL_EDITOR_WIDGET_ICON'                         => 'Icon',
    'DD_VISUAL_EDITOR_WIDGET_ICON_COLOR'                   => 'Farbe',
    'DD_VISUAL_EDITOR_WIDGET_ICON_CIRCLE'                  => 'Icon in einem Kreis darstellen',
    'DD_VISUAL_EDITOR_WIDGET_ICON_POS'                     => 'Position',
    'DD_VISUAL_EDITOR_WIDGET_ICON_POS_TOP'                 => 'Oben',
    'DD_VISUAL_EDITOR_WIDGET_ICON_POS_LEFT'                => 'Links',
    'DD_VISUAL_EDITOR_WIDGET_FULLWIDTH'                    => 'Fullwidth <small class="text-muted">(Experimentell)</small>',
    'DD_VISUAL_EDITOR_WIDGET_ARTICLE'                      => 'Artikel',
    'DD_VISUAL_EDITOR_WIDGET_CHOOSE_ARTICLE'               => 'Bitte w&auml;hlen Sie einen Artikel aus',
    'DD_VISUAL_EDITOR_WIDGET_CATEGORY'                     => 'Kategorie',
    'DD_VISUAL_EDITOR_WIDGET_CHOOSE_CATEGORY'              => 'Bitte w&auml;hlen Sie eine Kategorie aus',
    'DD_VISUAL_EDITOR_WIDGET_CLASS'                        => 'CSS-Klasse',
    'DD_VISUAL_EDITOR_WIDGET_CHOOSE_CLASS'                 => 'Geben Sie eine oder mehrere CSS-Klassen ein',
    'DD_VISUAL_EDITOR_HIDE_DEVICE'                         => 'Ausblenden',
    'DD_VISUAL_EDITOR_CHOOSE_HIDDEN_DEVICE'                => 'Bitte w&auml;hlen Sie ein Ger&auml;t aus',
    'DD_VISUAL_EDITOR_DEVICE_SMARTPHONE'                   => 'Smartphone (< 768px)',
    'DD_VISUAL_EDITOR_DEVICE_TABLET_PORTRAIT'              => 'Tablet (768px - 992px)',
    'DD_VISUAL_EDITOR_DEVICE_TABLET_LANDSCAPE'             => 'Kleiner Bildschirm (992px - 1200px)',
    'DD_VISUAL_EDITOR_DEVICE_DESKTOP'                      => 'Gro&szlig;er Bildschirm (> 1200px)',
    'DD_VISUAL_EDITOR_WIDGET_STYLE'                        => 'Aussehen',
    'DD_VISUAL_EDITOR_WIDGET_STYLE_TABS'                   => 'Tabs',
    'DD_VISUAL_EDITOR_WIDGET_STYLE_PILLS'                  => 'Pills',
    'DD_VISUAL_EDITOR_WIDGET_ANIMATION'                    => 'Animation',
    'DD_VISUAL_EDITOR_WIDGET_ANIMATION_NONE'               => 'Keine',
    'DD_VISUAL_EDITOR_WIDGET_ANIMATION_FADE'               => 'Einblenden',
    'DD_VISUAL_EDITOR_WIDGET_JUSTIFIED'                    => 'Tabs b&uuml;ndig ausrichten',
    'DD_VISUAL_EDITOR_WIDGET_BG_COLOR'                     => 'Hintergrundfarbe',
    'DD_VISUAL_EDITOR_WIDGET_BG_IMAGE'                     => 'Hintergrundbild',
    'DD_VISUAL_EDITOR_WIDGET_BG_FIXED'                     => 'Hintergrundbild fixieren',
    'DD_VISUAL_EDITOR_WIDGET_SPACE'                        => 'Abstand',
    'DD_VISUAL_EDITOR_WIDGET_SECONDS'                      => 'Sekunden',
    'DD_VISUAL_EDITOR_WIDGET_MINSTOCK'                     => 'Min. Bestand',
    'DD_VISUAL_EDITOR_WIDGET_MINPRICE'                     => 'Min. Preis',
    'DD_VISUAL_EDITOR_WIDGET_MAXPRICE'                     => 'Max. Preis',
    'DD_VISUAL_EDITOR_WIDGET_ONLYSALE'                     => 'Nur reduzierte Artikel',
    'DD_VISUAL_EDITOR_WIDGET_DISPLAY_DURATION'             => 'Anzeigedauer<br/><small class="text-muted">(in Minuten)</small>',
    'DD_VISUAL_EDITOR_WIDGET_DISPLAY_DURATION_HELP'        => 'Zeit nachdem sich der Artikel &auml;ndern soll (0 = bei jedem Aufruf)',
    'DD_VISUAL_EDITOR_WIDGET_RANDOM_SHOP_ARTICLE'          => 'Zuf&auml;lligen Shop Artikel verwenden, wenn kein Kategorie Artikel gefunden wurde',

    'DD_VISUAL_EDITOR_WIDGET_TABS'                         => 'Tabs',
    'DD_VISUAL_EDITOR_WIDGET_TABS_TOP'                     => 'Bestseller',
    'DD_VISUAL_EDITOR_WIDGET_TABS_NEW'                     => 'Neuerscheinungen',
    'DD_VISUAL_EDITOR_WIDGET_TABS_CATEGORY_SPECIAL'        => 'Spezial',
    'DD_VISUAL_EDITOR_WIDGET_TABS_CATEGORY_CATEGORIES'     => 'Kategorien',
    'DD_VISUAL_EDITOR_WIDGET_ARTICLE_COUNT'                => 'Anzahl',
    'DD_VISUAL_EDITOR_WIDGET_ARTICLE_TYPE'                 => 'Anzeigeart',
    'DD_VISUAL_EDITOR_WIDGET_ARTICLE_TYPE_GRID'            => 'Box',
    'DD_VISUAL_EDITOR_WIDGET_ARTICLE_TYPE_INFOGRID'        => 'Infobox',
    'DD_VISUAL_EDITOR_WIDGET_ARTICLE_TYPE_LINE'            => 'Zeile',

    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_TYPE'                => 'Typ',
    'DD_VISUAL_EDITOR_WIDGET_CHOOSE_CAROUSEL_TYPE'         => 'Bitte w&auml;hlen Sie einen Typ aus',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_TYPE_BRANDS'         => 'Hersteller',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_EXCLUDE'             => 'Auschlie&szlig;en',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_INCLUDE'             => 'Eingrenzen',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_EXCLUDE_INFO'        => 'Bezeichnung oder IDs durch \';\' getrennt auflisten',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_COUNT_PER_SLIDE'     => 'Anzahl pro Slide',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_COUNT'               => 'Gesamtanzahl',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_INTERVAL'            => 'Interval',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_ENABLE_ARROWS'       => 'Navigationspfeile anzeigen',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_ENABLE_BULLETS'      => 'Navigationspunkte anzeigen',
    'DD_VISUAL_EDITOR_WIDGET_CAROUSEL_IMG_GRAYSCALE'       => 'Graut&ouml;ne f&uuml;r Bilder aktivieren (Experimentell)',

    'DD_VISUAL_EDITOR_WIDGET_IMAGE'                        => 'Bild',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_TITLE'                  => 'Bezeichnung',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_SHOW_TITLE'             => 'Bezeichnung anzeigen',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_LINK_TYPE'              => 'Verkn&uuml;pft mit',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_LINK_TYPE_LIGHTBOX'     => 'Lightbox',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_LINK_TYPE_URL'          => 'URL',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_LINK_TYPE_NONE'         => 'Keine Verknüpfung',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_URL_NEW_WINDOW'         => 'Im neuen Fenster &ouml;ffnen <small class="text-muted">(nur bei URL Verkn&uuml;pfung)</small>',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_USE_THUMBNAIL'          => 'Thumbnail anzeigen',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_THUMBNAIL_SIZES'        => 'Thumbnail Gr&ouml;&szlig;e',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_THUMBNAIL_SIZES_SMALL'  => 'Klein (max. Breite von 185px)',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_THUMBNAIL_SIZES_MEDIUM' => 'Mittel (max. Breite von 300px)',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_THUMBNAIL_SIZES_LARGE'  => 'Gro&szlig; (max. Breite von 800px)',

    'DD_VISUAL_EDITOR_WIDGET_HERO_HEADLINE'                => '&Uuml;berschrift',
    'DD_VISUAL_EDITOR_WIDGET_HERO_FIXED'                   => 'Widget H&ouml;he an Fenstergr&ouml;&szlig;e anpassen',
    'DD_VISUAL_EDITOR_WIDGET_HERO_TEXT_COLOR'              => 'Textfarbe',
    'DD_VISUAL_EDITOR_WIDGET_HERO_CALL_TO_ACTION'          => 'CTA <br /><small class="text-muted">(Call-To-Action)</small>',
    'DD_VISUAL_EDITOR_WIDGET_HERO_CALL_TO_ACTION_URL'      => 'CTA URL',

    'DD_VISUAL_EDITOR_WIDGET_FORM_TITLE'                   => 'Titel',
    'DD_VISUAL_EDITOR_WIDGET_FORM_CONTENT'                 => 'Formular Felder',
    'DD_VISUAL_EDITOR_WIDGET_FORM_TYPE_VERTICAL'           => 'Label und Felder untereinander anzeigen',
    'DD_VISUAL_EDITOR_WIDGET_FORM_MAIL_TEMPLATE'           => 'E-Mail Vorlage',
    'DD_VISUAL_EDITOR_WIDGET_FORM_RECEIVER'                => 'Empf&auml;nger',

    'DD_VISUAL_EDITOR_WIDGET_EDIT'                         => 'Bearbeiten',
    'DD_VISUAL_EDITOR_WIDGET_DELETE'                       => 'L&ouml;schen',
    'DD_VISUAL_EDITOR_WIDGET_DELETE_CONFIRM'               => 'Wollen Sie das Widget wirklich l&ouml;schen?',
    'DD_VISUAL_EDITOR_WIDGET_DELETE_ALL_CONFIRM'           => 'Wollen Sie wirklich alle Widgets l&ouml;schen?',
    'DD_VISUAL_EDITOR_WIDGET_DUPLICATE'                    => 'Duplizieren',
    'DD_VISUAL_EDITOR_WIDGET_MOVE'                         => 'Verschieben',
    'DD_VISUAL_EDITOR_WIDGET_MOVETARGET'                   => 'Hierhin verschieben',

    'DD_VISUAL_EDITOR_WIDGET_ACTION'                       => 'Aktion',
    'DD_VISUAL_EDITOR_WIDGET_CHOOSE_ACTION'                => 'Bitte w&auml;hlen Sie eine Aktion aus',
    'DD_VISUAL_EDITOR_WIDGET_ACTION_NAME'                  => 'Titel',
    'DD_VISUAL_EDITOR_WIDGET_ACTION_SHORTDESC'             => 'Kurzbeschreibung',

    'DD_VISUAL_EDITOR_WIDGET_TREEVIEW_CONTENT'             => 'Root Knoten',
    'DD_VISUAL_EDITOR_WIDGET_TREEVIEW_CHOOSE_CONTENT'      => 'Bitte w&auml;hlen Sie einen CMS-Inhalt aus',
    'DD_VISUAL_EDITOR_WIDGET_TREEVIEW_TITLE'               => 'Titel',

    'DD_VISUAL_EDITOR_SHORTCODE_FORM'                      => 'Formular',
    'DD_VISUAL_EDITOR_SHORTCODE_TEXT'                      => 'Text',
    'DD_VISUAL_EDITOR_SHORTCODE_ARTICLE'                   => 'Artikel',
    'DD_VISUAL_EDITOR_SHORTCODE_CATEGORY'                  => 'Kategorie',
    'DD_VISUAL_EDITOR_SHORTCODE_TABS'                      => 'Tabs',
    'DD_VISUAL_EDITOR_SHORTCODE_ICON'                      => 'Icon',
    'DD_VISUAL_EDITOR_SHORTCODE_SPACER'                    => 'Spacer',
    'DD_VISUAL_EDITOR_SHORTCODE_CAROUSEL'                  => 'Karussell',
    'DD_VISUAL_EDITOR_SHORTCODE_IMAGE'                     => 'Bild',
    'DD_VISUAL_EDITOR_SHORTCODE_HERO'                      => 'Hero',
    'DD_VISUAL_EDITOR_SHORTCODE_ACTION'                    => 'Aktion',
    'DD_VISUAL_EDITOR_SHORTCODE_RANDOM_ARTICLE'            => 'Zuf&auml;lliger Artikel',
    'DD_VISUAL_EDITOR_SHORTCODE_TREEVIEW'                  => 'Baumstruktur',

    'DD_VISUAL_EDITOR_LANG_CHANGE_MSG'                     => 'Wenn Sie die Sprache wechseln, gehen alle nicht gespeicherten &Auml;nderungen verloren. Sie k&ouml;nnen nun zwischen folgenden Optionen w&auml;hlen:<br><br>
                                                               <ul>
                                                                 <li><strong>Sprache laden</strong><br>Nicht gespeicherte &Auml;nderungen gehen verloren und die Seite wird in der ausgew&auml;hlten Sprache geladen
                                                                 <li><strong>Inhalt &uuml;bernehmen</strong><br>Die aktuellen Daten werden f&uuml;r die ausgew&auml;hlte Sprache &uuml;bernommen. Wenn bereits Daten in der Sprache vorhanden sind, werden diese &uuml;berschrieben.
                                                                 <li><strong>Abrechen</strong>
                                                               </ul>',
    'DD_VISUAL_EDITOR_LANG_CHANGE_TITLE'                   => 'Sprache wechseln',
    'DD_VISUAL_EDITOR_LANG_CHANGE_CANCEL'                  => 'Abrechen',
    'DD_VISUAL_EDITOR_LANG_CHANGE_OVERWRITE'               => 'Inhalt &uuml;bernehmen',
    'DD_VISUAL_EDITOR_LANG_CHANGE_OVERWRITE_CONFIRM'       => 'Es ist bereits Inhalt in <strong>%s</strong> vorhanden. Sind Sie sicher, dass Sie den Inhalt &uuml;berschreiben wollen?',
    'DD_VISUAL_EDITOR_LANG_CHANGE_LOAD'                    => 'Sprache laden',
    'DD_VISUAL_EDITOR_NO_LANG_INFO'                        => 'Die Seite ist in dieser Sprache noch nicht vorhanden. Die Daten wurden von <strong>%s</strong> &uuml;bernommen.',

    'DD_VISUAL_EDITOR_DELETE'                              => 'L&ouml;schen',
    'DD_VISUAL_EDITOR_DELETE_CONFIRM'                      => 'Wollen Sie den Inhalt wirklich L&ouml;schen?',
    'DD_VISUAL_EDITOR_EDIT'                                => 'Inhalte bearbeiten',
    'SHOP_MODULE_blEnableVisualEditorBlocks'               => 'Dynamische Bl&ouml;cke aktivieren (Voraussetzung: "veblock" Tags m&uuml;ssen im Theme gesetzt sein)',
    'SHOP_MODULE_sVisualEditorCronKey'                     => 'Cronjob Schl&uuml;ssel',
    'SHOP_MODULE_aPredefinedCssClasses'                    => 'Vordefinierte CSS-Klassen',
    'SHOP_MODULE_iDefaultWidgetSize'                       => 'Standard Breite beim Anlegen von Widgets',
    'SHOP_MODULE_ddoeVisualCmsAlternativeImageDirectory' => 'Alternatives Bildverzeichnis',
    'DD_VISUAL_EDITOR_ADD_COLUMN'                          => 'Spalte hinzuf&uuml;gen',
    'DD_VISUAL_EDITOR_TEMPLATES'                           => 'Vorlagen',
    'DD_VISUAL_EDITOR_TEMPLATE'                            => 'Vorlage',
    'DD_VISUAL_EDITOR_CUSTOM_CSS'                          => 'Individuelles CSS / LESS',
    'DD_VISUAL_EDITOR_GLOBAL_CSS_CLASS'                    => 'Globale CSS-Klasse',

    'DD_VISUAL_EDITOR_RESPONSIVE_COLUMNS'                  => 'Spalten',
    'DD_VISUAL_EDITOR_RESPONSIVE_COLUMN'                   => 'Spalte',
    'DD_VISUAL_EDITOR_WIDGET_MAIN_SETTINGS'                => 'Allgemeine Einstellungen',
    'DD_VISUAL_EDITOR_WIDGET_DESIGN_SETTINGS'              => 'Designeinstellungen',
    'DD_VISUAL_EDITOR_DEVICE'                              => 'Ger&auml;t',
    'DD_VISUAL_EDITOR_COLUMN_OFFSET'                       => 'Versatz (Offset)',
    'DD_VISUAL_EDITOR_COLUMN_WIDTH'                        => 'Breite',
    'DD_VISUAL_EDITOR_NO_COLUMN_OFFSET'                    => 'Kein Versatz',
    'DD_VISUAL_EDITOR_COLUMN_INHERIT'                      => 'Geerbt (Standard)',
    'DD_VISUAL_EDITOR_COLUMN_DEFAULT'                      => 'Standard',
    'DD_VISUAL_EDITOR_WIDGET_RESPONSIVE_SETTINGS'          => 'Responsive Einstellungen',

    'DD_VISUAL_EDITOR_WIDGET_IMAGES'                       => 'Bilder',
    'DD_VISUAL_EDITOR_WIDGET_IMAGE_LINK_TYPE_IMAGE_URL'    => 'Bild URL',
    'DD_VISUAL_EDITOR_WIDGET_DELETE_NESTED_CONFIRM'        => 'Wollen Sie die Spalte und alle Widgets innerhalb wirklich l&ouml;schen?',
    'DD_VISUAL_EDITOR_NESTED_COLUMN_WARNING'               => 'Verschachtelung von Spalten nicht m&ouml;glich!',
    'DD_VISUAL_EDITOR_NO_SPACE_WARNING'                    => 'Hinzuf&uuml;gen nicht m&ouml;glich! Kein Platz vorhanden.',
    'DD_VISUAL_EDITOR_WIDGET_ADD_FIELD'                    => 'Feld hinzuf&uuml;gen',
    'DD_VISUAL_EDITOR_SHORTCODE_IMAGE_GALLERY'             => 'Galerie',

    'DD_VISUAL_EDITOR_SAVE_CURRENT_TEMPLATE'               => 'Aktuelles Layout als Vorlage speichern',
    'DD_VISUAL_EDITOR_TEMPLATE_NAME'                       => 'Name',
    'DD_VISUAL_EDITOR_TEMPLATE_DATE'                       => 'Erstellungsdatum',
    'DD_VISUAL_EDITOR_NO_TEMPLATES_FOUND'                  => 'Keine Vorlagen vorhanden',
    'DD_VISUAL_EDITOR_DELETE_TEMPLATE_CONFIRM'             => 'Wollen Sie die Vorlage wirklich l&ouml;schen?',
    'DD_VISUAL_EDITOR_APPLY_TEMPLATE_CONFIRM'              => 'Vorlage &uuml;bernehmen? Das aktuelle Layout wird damit &uuml;berschrieben.',
    'DD_VISUAL_EDITOR_SAVED_TEMPLATES'                     => 'Gespeicherte Vorlagen',
    'DD_VISUAL_EDITOR_TEMPLATE_TIMER_DATE'                 => 'Datum',
    'DD_VISUAL_EDITOR_TEMPLATE_TIMER'                      => 'Zeitsteuerung',
    'DD_VISUAL_EDITOR_TEMPLATE_TIMER_INFO'                 => 'Bei aktiver Zeitsteuerung wird der Inhalt des ausgew&auml;hlten CMS-Inhalts mit dem Inhalt der Vorlage zum angegebenen Datum ersetzt. Voraussetzung ist die Aktivierung des Cronjobs des Moduls.',
    'DD_VISUAL_EDITOR_TEMPLATE_TIMER_ACTIVE_INFO'          => 'Zeitsteuerung f&uuml;r <strong>%s</strong> am %s um %s Uhr',

    'DD_VISUAL_EDITOR_ACTIVE_TIMESPAN_SELECT'              => 'Zeitraum ausw&auml;hlen',
    'DD_VISUAL_EDITOR_ACTIVE_TIMESPAN_HIDE'                => 'Zeitraum ausblenden',
    'DD_VISUAL_EDITOR_ACTIVE_TIMESPAN_FROM'                => 'Aktiv von',
    'DD_VISUAL_EDITOR_ACTIVE_TIMESPAN_UNTIL'               => 'Aktiv bis',
    'DD_VISUAL_EDITOR_ACTIVE_TIMESPAN_INFO'                => 'Um einen Aktiv-Zeitraum zu nutzen, muss der Aktiv-Haken gesetzt sein.',

    'DD_VISUAL_EDITOR_DEMODATA_INSTALL'                    => 'Demodaten installieren',
    'DD_VISUAL_EDITOR_DEMODATA_INSTALLED'                  => 'Demodaten installiert!',
    'DD_VISUAL_EDITOR_LOAD_DEMODATA'                       => 'Demodaten laden',
    'DD_VISUAL_EDITOR_LOAD_DEMODATA_INFO'                  => 'Wollen Sie die Demodatan laden? Alle ungespeicherten Änderungen des aktuellen Datensatzes gehen dabei verloren.',

    'DD_VISUAL_EDITOR_TREEVIEW'                            => 'CMS-Inhalte',
    'DD_VISUAL_EDITOR_TREEVIEW_MAIN_TAB'                   => 'Seiten',
    'DD_VISUAL_EDITOR_TREEVIEW_SNIPPETS_TAB'               => 'Snippets',
    'DD_VISUAL_EDITOR_TREEVIEW_LOAD_CONTENT'               => 'Inhalt laden',
    'DD_VISUAL_EDITOR_TREEVIEW_NO_RESULTS'                 => 'Keine Inhalte gefunden! Versuchen Sie eine andere Suchanfrage.',

    // Help

    'HELP_CONTENT_MAIN_MANUAL'                             => 'Wenn Sie Manuell auswählen, wird ein Link erzeugt, mit dem Sie die CMS-Seite in andere CMS-Seiten einbinden können. Der Link wird im Tab \'Einstell.\' unten angezeigt, wenn Sie auf Speichern klicken.',

    // Base Module

    'DD_CLOSE'                                             => 'Schlie&szlig;en',
    'DD_CANCEL'                                            => 'Abbrechen',
    'DD_APPLY'                                             => '&Uuml;bernehmen',
    'DD_OK'                                                => 'OK',
    'DD_CONFIRM_DIALOG'                                    => 'Best&auml;tigung erforderlich!',
    'DD_CONFIRM'                                           => 'Best&auml;tigen',

    'DD_MEDIA_DIALOG'                                      => 'Mediathek',
    'DD_MEDIA_LIST'                                        => 'Medien',
    'DD_MEDIA_UPLOAD'                                      => 'Upload',
    'DD_MEDIA_REMOVE'                                      => '<i class="fa fa-times-circle"></i> Datei unwiderruflich l&ouml;schen',
    'DD_MEDIA_REMOVE_CONFIRM'                              => 'M&ouml;chten Sie die Datei wirklich l&ouml;schen?',
    'DD_MEDIA_FALLBACK_INFO'                               => 'Datei ausw&auml;hlen <strong>f&uuml;r den Upload</strong>',
    'DD_MEDIA_UPLOAD_INFO'                                 => 'Datei hierhin ziehen <strong>f&uuml;r den Upload</strong><br><small>oder hier klicken</small>',
    'DD_MEDIA_DRAG_INFO'                                   => 'Datei hierhin ziehen <strong>f&uuml;r den Upload</strong>',
    'DD_MEDIA_EMPTY_LIST'                                  => 'Keine Medien vorhanden',
    'DD_MEDIA_FILETYPE_NOT_ALLOWED'                        => 'Dateiformat nicht erlaubt!',
    'DD_MEDIA_FILES_FOUND'                                 => 'Dateien in der Mediathek',
    'DD_MEDIA_MULTIPLE_INFO'                               => 'STRG + Mausklick f&uuml;r Mehrfachauswahl',

    'DD_MEDIA_EXCEPTION_INVALID_FILEEXT'                   => 'Der Upload von Dateien mit dieser Dateiendung ist nicht erlaubt!',

);
